
services:
  manejo_clientes:
    build: ManejoClientes
    ports:
      - "9090:9090"
    environment:
      DB_URL: jdbc:mysql://manejoCli:3306/gestion_clientes?createDatabaseIfNotExist=true
      DB_USER_NAME: root
    restart: always
    depends_on:
      - manejoCli

  manejoCli:
    image: mysql:8.0.33
    ports:
      - "3306:3306" # O bien "3306:3306" si no hay conflictos
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gestion_clientes
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
